version: '3.9'
# MYSQL

name: kanboard

services:

  kanboard:
    image: kanboard/kanboard:latest
    volumes:
      - ./kanboard_data:/var/www/app/data
      - ./kanboard_plugins:/var/www/app/plugins
    environment:
      DATABASE_URL: mysql://kanboard:kk@kanboard-db/kanboard
      PLUGIN_INSTALLER: true

  kanboard-db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: kk
      MYSQL_DATABASE: kanboard
      MYSQL_USER: kanboard
      MYSQL_PASSWORD: kk
    volumes:
      - ./db:/var/lib/mysql

networks:
  default:
    name: proxy-net
    external: true