services:
  bind:
    image: internetsystemsconsortium/bind9:9.21
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 953:953
    volumes:
      - ./dns-config:/etc/bind
      - ./resolv.conf:/etc/resolv.conf
#    network_mode: host
#      - ./cache-bind:/var/cache/bind
#      - ./var-lib:/var/lib/bind
#      - ./var-log:/var/log
