services:
  gitlab:
    image: gitlab/gitlab-ce:16.11.10-ce.0
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = 'your_password'
      # Херня с паролем - не работает!!!
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    #   - ./ssl:/etc/gitlab/ssl
    shm_size: '256m'