version: '3.9'

name: proxy-and-app

services:
  httpd1:
    image: httpd
    hostname: httpd1

  nginx:
    image: nginx
    hostname: nginx
    ports:
      - 443:443
    volumes:
      - ./nginx/selfsigned/:/etc/ssl/selfsigned:ro
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro

networks:
  default:
    name: app-net