# Only HTTP
# No Password authentification

services:
  sish:
    image: antoniomika/sish:latest
    container_name: sish
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./pubkeys:/pubkeys
      - ./keys:/keys
      - ./ssl:/ssl
    command: |
      --ssh-address=:2222
      --http-address=:80
      --authentication-keys-directory=/pubkeys
      --private-keys-directory=/keys
      --bind-random-ports=false
      --bind-random-subdomains=false
      --domain=sish.atom25.local
    network_mode: host
    restart: always
