# version: '3.9'

name: proxy

services:
  n1:
    image: nginx
    hostname: nginx
    container_name: nginx
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/:/etc/openssl/proxy:ro
      - ./nginx/.htpasswd/:/etc/nginx/.htpasswd:ro
    ports:
      - 443:443/tcp
      # - 80:80/tcp
    
networks:
  default:
    name: proxy-net
    external: true