services:
  bind:
    image: internetsystemsconsortium/bind9:9.21
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 953:953
    volumes:
      - ./dns-config:/etc/bind
      - ./resolv.conf:/etc/resolv.conf
      - bind-cache:/var/cache/bind
      - bind-lib:/var/lib/bind
      - bind-log:/var/log
    restart: always

volumes:
  bind-cache:
  bind-lib:
  bind-log: