# Взят из https://github.com/0xJacky/nginx-ui?tab=readme-ov-file#:~:text=%D0%A1%D0%BE%D0%B7%D0%B4%D0%B0%D0%B9%D1%82%D0%B5%20%D1%84%D0%B0%D0%B9%D0%BB%20docker%2Dcompose.yml%20%D1%81%D0%BB%D0%B5%D0%B4%D1%83%D1%8E%D1%89%D0%B8%D0%BC%20%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%BE%D0%BC%3A

services:
  nginx-ui:
    stdin_open: true
    tty: true
    container_name: nginx-ui
    restart: always
    environment:
      - TZ=Europe/Moscow
    volumes:
      - './etc/nginx:/etc/nginx'
      - './etc/nginx-ui:/etc/nginx-ui'
      - '/var/www:/var/www'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './log/nginx:/var/log/nginx'
    network_mode: host
    image: 'uozi/nginx-ui:latest'

